online-mode=false
server-port=55916
gamemode=survival
difficulty=normal
pvp=true
spawn-protection=0
allow-flight=true
max-players=10
view-distance=10
simulation-distance=8
white-list=false
enable-query=false
enable-rcon=false
level-name=world
motd=ClonesSMP - AI Celebrity Bots
